### ISSUE TITLE
Listen to onhashchange to enable forward/back navigation

### ISSUE THREAD

**Issue by ssorallen** [kevinsawicki/birthday-pizza#5]
Awesome page! ✨💥🎉

I changed to a few different birthdays and noticed the hash changes, which add items to the history, but the page doesn't listen for hash changes to support forward/back buttons.

**Comment by kevinsawicki** [comment]
Oh, great idea :+1: :pizza: 

If you are interested in adding this, a pull request would be much appreciated.
